name: WasteBot Scheduler

on:
  workflow_dispatch:
    inputs:
      time:
        description: "evening / morning"
        required: true
        default: "evening"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Scheduler działa"
