name: WasteBot Scheduler

on:
  schedule:
    - cron: "0 18 * * *"   # 18:00 UTC → 20:00 PL czasu letniego
    - cron: "0 4 * * *"    # 04:00 UTC → 06:00 PL czasu letniego
  workflow_dispatch:

jobs:
  call-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Evening reminder
        if: github.event.schedule == '0 18 * * *'
        run: |
          curl -X POST "https://wierzchucino-bot.onrender.com/runScheduler?time=evening"

      - name: Morning reminder
        if: github.event.schedule == '0 4 * * *'
        run: |
          curl -X POST "https://wierzchucino-bot.onrender.com/runScheduler?time=morning"
