name: Waste Scheduler

on:
  schedule:
    - cron: "0 6 * * *"     # 06:00 każdego dnia → morning
    - cron: "0 18 * * *"    # 18:00 każdego dnia → evening
  workflow_dispatch:

jobs:
  run-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Wywołanie schedulera (morning)
        if: github.event.schedule == '0 6 * * *'
        run: |
          curl -X GET "https://wierzchucino-bot.onrender.com/runScheduler?time=morning"

      - name: Wywołanie schedulera (evening)
        if: github.event.schedule == '0 18 * * *'
        run: |
          curl -X GET "https://wierzchucino-bot.onrender.com/runScheduler?time=evening"
